[project]
name = "project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain-community>=0.4.1",
    "langchain-upstage>=0.7.6",
    "langgraph>=1.0.7",
    "python-dotenv>=1.2.1",
    "pytest>=9.0.2",
    "plotly>=6.5.2",
    "pandas>=2.2.3",
    "kaleido>=0.2.1",
]

[dependency-groups]
dev = [
    "ddgs>=9.10.0",
    "ipykernel>=7.1.0",
    "jupyter>=1.1.1",
    "langchain[google-genai]>=1.2.8",
    "langchain-tavily>=0.2.17",
]